### ISSUE TITLE
Specification of audio format files

### ISSUE THREAD

**Issue by ssosas** [linto-ai/linto-desktoptools-hmg#5]
Dear all,
Could you be more specific about the format of audio files required?
- extension (MP3, WAV, etc)??
- recommended format (frequency sampling, duration, etc), what have you used for LinTO generation? 
- Does the duration need to be exactly the same? Are some millis of difference  authorized?
- may I have access to some examples?

thanks a lot!
Sergio

**Comment by Lokhozt** [comment]
Hello,
- For now only .wav 16 kHz mono 2B files are supported.
- Duration can vary slightly, longer samples are trimmed, shorter samples are ignored in this version.
- We provide our data [there](https://dl.linto.ai/downloads/datasets/).

Note that the current available release is not up to date and the new version is still a work in progress.

Cheers

**Comment by JulianGerhard21** [comment]
Hi @Lokhozt ,

thanks for clarification. I am currently running it on Ubuntu 20.04 and I am providing samples in the form of:

`{"file_name": "u_xxx.wav", "label": "test", "attr": null}`

Is this correct? Because if I do so and want to evaluate the data with `Analyze Samples`, your tool tells me that several files couldnt be found and crashes. After debugging those files, I found out, that the tool seemed to mix up the labelled files meaning that a sample containing the hotword was used as a sample for the non-hotword and hence couldnt be found in the specified directory.

I am a bit desparate because I tried a lot of situations/fixes but nothing seem to work. Would it be a problem to send you the files to simply train a model for me?

Kind regards
Julian

**Comment by Lokhozt** [comment]
Hello Julian,
Sorry for the delay i'm deep into 1.0 code and i missed the notification.
Do you have a console trace of the error ?

**Comment by JulianGerhard21** [comment]
Hi @Lokhozt ,

unfortunately, the tool can't be restarted now. I have attached the audio files in a zip, both the labelled ones and the noise.
It would be a huge favor if you could quickly train a model with them... shouldn't last long. I'll wait until the release of 1.0 then.

[audio_files.zip](https://github.com/linto-ai/linto-desktoptools-hmg/files/5860682/audio_files.zip)

I simply want to test something so a perfect quality is absolutely not necessary... I hope you are able to help! 

The error was a bit weird. Basically the tool told me that it could not find a bunch of files. The weird thing is, that I added them previously. After debugging the error (no stacktrace, just the error) I realised that the connection between the label and the actual filepath was mixed up.

Kind regards and many thanks
Julian

**Comment by Lokhozt** [comment]
Hello Julian, 
I have trouble with your samples, cannot open them properly. Cannot play them neither.
